FROM alpine:{{ env.alpineVer }} AS curl-builder

RUN apk upgrade \
    && apk add --no-cache alpine-sdk

RUN mkdir -p /var/cache/distfiles \
    && chmod a+w /var/cache/distfiles

WORKDIR /root

RUN abuild-keygen -an \
    && cp /root/.abuild/-*.rsa.pub /etc/apk/keys/

COPY curl/* /root/

RUN abuild -Fr

