FROM alpine:{{ env.alpineVer }} AS curl-builder

RUN apk upgrade \
    && apk add alpine-sdk

{{ if env.version == "8.0" then ( -}}
COPY --from=openssl1-builder /root/packages/x86_64 /openssl1-packages
COPY --from=openssl1-builder /etc/apk/keys/-*.rsa.pub /etc/apk/keys/
RUN apk add /openssl1-packages/*.apk
#RUN ln -s /usr/bin/openssl1.1 /usr/bin/openssl
{{ ) else "" end -}}

RUN mkdir -p /var/cache/distfiles \
    && chmod a+w /var/cache/distfiles

WORKDIR /root

RUN abuild-keygen -an \
    && cp /root/.abuild/-*.rsa.pub /etc/apk/keys/

COPY CURL_APKBUILD /root/APKBUILD

RUN abuild -Fr

